name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
          cache: true

      - name: Publish package
        run: deno publish

      - run: deno pack --output typebox.tgz

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: tar -xzf typebox.tgz
      - working-directory: package
        run: |
          npm pkg set repository.url="git+https://github.com/jiang-zhexin/typebox.git"
          npm publish --tag alpha

  releases:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: npx ts-json-schema-generator --path rule_set.ts --type "rule_set" -o rule_set.json

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          files: |
            sing-box/docs/schema.json
            rule_set.json
